### ISSUE TITLE
Reading string values keeps firing error

### ISSUE THREAD

**Issue by jmsfcb** [danigm/epub-rs#1]
I'm trying to suss out an issue I am having. Every time I attempt to read a string value from an epub I get the following error. _Specified file not found in archive_

```rust
let doc = EpubDoc::new(input_file);
    assert!(doc.is_ok());
    let mut doc = doc.unwrap();
    {
        let title = doc.metadata.get("Title");
        println!("Book title {:?}", title);
    }
    let len_pages = doc.resources.len();
    println!("Num Pages: {}", len_pages);

    let len = doc.spine.len();
    for i in 1..len {
        let n = doc.go_next();
        match n {
            Ok(v) => {
                println!("ID: {}", doc.get_current_id().unwrap());
                let current = doc.get_current_str();
                match current {
                    Ok(v) => println!("Value {:?}", v), 
                    Err(e) => println!("Text Err {:?}", e.description()) /*Specified file not found in archive*/
                }
            },
            Err(e) => println!("General Error: {:?}", e),
        }
    }
```

I pulled a sample book from [here](https://pressbooks.com/sample-books/) to make sure the book I had locally wasn't corrupted.

**Comment by danigm** [comment]
I've fixed the problem. These books have the root file in the zip root directory and the path wasn't built correctly. It's fixed in this commit: https://github.com/danigm/epub-rs/commit/6a616bcbb4e282f317c60eda21711a5589d1f55f

I've added a test with your code: 
https://github.com/danigm/epub-rs/blob/master/tests/read.rs

You can run this test with:
```
$ cargo test -- --nocapture read_doc
```

Your code should work with the latest release 1.0.5
